### ISSUE TITLE
Ignoring Carriage Returns

### ISSUE THREAD

**Issue by mikekeith52** [ogrodnek/csv-serde#33]
I have an issue where within my csv file I have random lines where the input is quoted, but the end quote ends with a carriage return. So the value is essentially coded "value\r". When Hive ingests this file, it begins a new line where really, the carriage return should be ignored. Does your library offer a solution for such a problem? Thanks,

**Comment by ogrodnek** [comment]
Sorry @mikekeith52 , by the time it gets to the SerDe the lines are already split.
